### ISSUE TITLE
主页上点a标签没有导入正确地地址

### ISSUE THREAD

**Issue by lewis-geek** [lewis-geek/MyFristPage#1]
主页上的a标签没有正确添加链接

**Comment by GIS90** [comment]
about页面：如果需要生成 about 页面，需要在 source 目录下创建一个 about 目录，并在 about 目录下创建一个 index.md 文件，为该文件添加 layout: about 属性。此时就可在 <your_url>/about 路径访问到 about 页面了。


怎么处理的，方便留个邮箱进行交流吗
